services:
  - type: web
    name: bhubaneswar-cd-api
    runtime: python
    region: singapore          # closest to India
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEE_PROJECT_ID
        value: change-detection-494607
      - key: GEE_CREDENTIALS_JSON
        sync: false            # Set this secret in the Render dashboard
